# Generated by Django 5.1 on 2024-08-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sms_type', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('sms_body', models.TextField()),
                ('sent_by', models.CharField(max_length=150)),
            ],
        ),
    ]
