# Generated by Django 5.1 on 2024-08-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('primary_setup', '0017_dpsscheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electric_bill', 'Electric Bill'), ('gust_snack', 'Gust Snack'), ('wifi_bill', 'WiFi Bill'), ('staff_salary', 'Staff Salary'), ('bazar', 'Bazar'), ('house_rent', 'House Rent')], max_length=50)),
                ('CustomerName', models.CharField(max_length=100)),
                ('VoucherID', models.CharField(editable=False, max_length=50, unique=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ExpenseBy', models.CharField(max_length=50)),
                ('IsCalculateWithLossProfit', models.BooleanField()),
                ('ExpenseDate', models.DateField()),
                ('Note', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_setup.branch')),
                ('somity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_setup.somity')),
            ],
        ),
    ]
