# Generated by Django 5.1 on 2024-08-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrans', '0002_alter_expense_category'),
        ('primary_setup', '0017_dpsscheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('processing_fee', 'Processing Fee'), ('service_charge', 'Service Charge'), ('insurance_fee', 'Insurance Fee'), ('others_cost', 'Others cost'), ('member_account_income', 'Member Account Income'), ('bank_account_income', 'Bank Account Income')], max_length=50)),
                ('CustomerName', models.CharField(max_length=100)),
                ('VoucherID', models.CharField(editable=False, max_length=50, unique=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IncomeBy', models.CharField(max_length=50)),
                ('IsCalculateWithLossProfit', models.BooleanField()),
                ('IncomeDate', models.DateField()),
                ('Note', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_setup.branch')),
                ('somity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_setup.somity')),
            ],
        ),
    ]
