# Generated by Django 5.1 on 2024-08-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrans', '0006_passbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='passbook',
            name='Category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
