# Generated by Django 5.1 on 2024-08-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrans', '0009_ssm_withdraw'),
        ('primary_setup', '0023_bank_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetOutLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(choices=[('somity1', 'Somity 1'), ('somity2', 'Somity 2'), ('somity3', 'Somity 3')], max_length=100)),
                ('date', models.DateField()),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('processed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('VoucherID', models.CharField(editable=False, max_length=50, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_setup.branch')),
            ],
        ),
    ]
