# Generated by Django 5.1 on 2024-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrans', '0011_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='processed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
