# Generated by Django 5.1 on 2024-08-26 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrans', '0012_salary_processed_by'),
        ('primary_setup', '0023_bank_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='primary_setup.branch'),
            preserve_default=False,
        ),
    ]
