# Generated by Django 5.1 on 2024-08-27 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrans', '0016_profitdistribution'),
        ('primary_setup', '0025_alter_vouchercategory_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='voucher_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='primary_setup.vouchercategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='voucher_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='primary_setup.vouchercategory'),
            preserve_default=False,
        ),
    ]
