# Generated by Django 5.1 on 2024-08-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otrans', '0017_expense_voucher_category_income_voucher_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
    ]
