# Generated by Django 5.1 on 2024-08-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrans', '0018_remove_expense_category_remove_income_category'),
        ('primary_setup', '0026_alter_vouchercategory_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='getoutloan',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='primary_setup.outloan'),
            preserve_default=False,
        ),
    ]
