# Generated by Django 5.1 on 2025-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrans', '0020_remove_getoutloan_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='IsCalculateWithLossProfit',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
