# Generated by Django 5.1 on 2025-01-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrans', '0021_alter_expense_iscalculatewithlossprofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='ExpenseDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
