# Generated by Django 5.1 on 2025-01-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otrans', '0022_alter_expense_expensedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='IncomeDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='IsCalculateWithLossProfit',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
