# Generated by Django 5.1 on 2024-08-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0004_customuser_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='somity_group',
        ),
        migrations.AddField(
            model_name='customuser',
            name='somity_group',
            field=models.ManyToManyField(blank=True, to='primary_setup.somity'),
        ),
    ]
