# Generated by Django 5.1 on 2024-08-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0005_remove_customuser_somity_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
