# Generated by Django 5.1 on 2024-08-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0006_remove_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='joining_date',
        ),
    ]
