# Generated by Django 5.1 on 2024-08-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0010_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('profit_rate', models.IntegerField()),
                ('loan_duration', models.IntegerField()),
                ('max_loan_amount', models.IntegerField()),
            ],
        ),
    ]
