# Generated by Django 5.1 on 2024-08-16 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0011_loancategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='director_photos')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='primary_setup.branch')),
            ],
        ),
    ]
