# Generated by Django 5.1 on 2024-08-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0012_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
