# Generated by Django 5.1 on 2024-08-16 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0013_director_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('balance', models.FloatField()),
                ('profit', models.FloatField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outloan', to='primary_setup.branch')),
            ],
        ),
    ]
