# Generated by Django 5.1 on 2024-08-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0014_outloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSES', 'Expenses')], default='Income', max_length=50)),
                ('category_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
    ]
