# Generated by Django 5.1 on 2024-08-16 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0015_vouchercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancategory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Loan', to='primary_setup.branch'),
        ),
        migrations.CreateModel(
            name='FDRScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
                ('scheme_type', models.CharField(choices=[('FIXED', 'Fixed Profit'), ('MONTHLY', 'Monthly Profit')], max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('profit_percent', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FDR', to='primary_setup.branch')),
            ],
        ),
    ]
