# Generated by Django 5.1 on 2024-08-16 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0016_loancategory_branch_fdrscheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPSScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
                ('payment_sequence', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DPS', to='primary_setup.branch')),
            ],
        ),
    ]
