# Generated by Django 5.1 on 2024-08-22 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0020_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpsscheme',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DPS_Scheme', to='primary_setup.branch'),
        ),
        migrations.AlterField(
            model_name='fdrscheme',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FDR_Scheme', to='primary_setup.branch'),
        ),
    ]
