# Generated by Django 5.1 on 2024-08-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0022_alter_fdrscheme_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
