# Generated by Django 5.1 on 2024-08-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0024_vouchercategory_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchercategory',
            name='category_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='Income', max_length=50),
        ),
    ]
