# Generated by Django 5.1 on 2024-08-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0025_alter_vouchercategory_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchercategory',
            name='category_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=50),
        ),
    ]
