# Generated by Django 5.1 on 2024-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0026_alter_vouchercategory_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('on', 'On'), ('off', 'Off')], max_length=3)),
                ('language', models.CharField(choices=[('bangla', 'Bangla'), ('english', 'English')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content_english', models.TextField()),
                ('content_bengali', models.TextField()),
            ],
        ),
    ]
