# Generated by Django 5.1 on 2024-09-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0027_smssetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smssetting',
            name='action',
        ),
    ]
