# Generated by Django 5.1 on 2024-09-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0028_remove_smssetting_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smssetting',
            name='content_english',
        ),
        migrations.RemoveField(
            model_name='smssetting',
            name='language',
        ),
    ]
