# Generated by Django 5.1 on 2024-09-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary_setup', '0031_alter_customuser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
    ]
