# Generated by Django 5.1 on 2024-08-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_userlog_cashflow_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='action',
            field=models.IntegerField(choices=[(1, 'Login'), (2, 'Logout'), (3, 'Changed Password'), (4, 'Add Role'), (5, 'Edit Role'), (6, 'Role Delete'), (7, 'Add Staff'), (8, 'Edit Staff'), (9, 'Staff Delete'), (10, 'Staff Change Password'), (19, 'Add Area'), (20, 'Edit Area'), (21, 'Add Bank'), (22, 'Edit Bank'), (23, 'Add Voucher Category'), (24, 'Edit Voucher Category'), (25, 'Add Member'), (26, 'Edit Member'), (27, 'Delete General AC Transaction'), (28, 'Add DPS AC'), (29, 'Edit DPS AC'), (30, 'Add FDR AC'), (31, 'Add Loan AC'), (32, 'Common Collection'), (33, 'Deposit General AC'), (34, 'Installment Collection'), (35, 'Deposit DPS'), (36, 'Bank Withdraw'), (37, 'Deposit FDR'), (38, 'Withdraw General AC'), (39, 'Withdraw DPS AC'), (40, 'DPS AC Closed'), (41, 'Bank Deposit'), (42, 'FDR Balance Withdraw'), (43, 'FDR Profit Withdraw'), (44, 'FDR Closing'), (45, 'Delete Loan AC Transaction'), (46, 'Add General Expense'), (47, 'Delete General Expense'), (48, 'Salary Distribution'), (49, 'Staff Security Money Deposit'), (50, 'Staff Security Money Withdraw'), (51, 'Staff Balance Withdraw'), (52, 'Delete Staff Salary'), (53, 'Add Director'), (54, 'Edit Director'), (55, 'Delete Director'), (56, 'Deposit from Director'), (57, 'Withdraw for Director'), (58, 'Add Out Loan'), (59, 'Edit Out Loan'), (60, 'Delete Out Loan'), (61, 'Delete Out Loan Transaction'), (62, 'Out Loan Received'), (63, 'Out Loan Paid'), (64, 'Delete Director Transaction'), (65, 'Somity Wise Installment Collection'), (66, 'Somity Wise General A/C Deposit'), (67, 'Somity Wise DPS Deposit'), (68, 'Bank Withdraw Delete'), (69, 'Bank Deposit Delete'), (70, 'Loan Closing'), (71, 'Installment Collection from General Savings'), (72, 'Delete Loan Account'), (73, 'Delete DPS Account'), (74, 'Delete FDR Account'), (75, 'Delete Member'), (76, 'Delete FDR AC Transaction'), (77, 'Add CC Loan AC'), (78, 'Delete CC Loan AC Transaction'), (79, 'CC Loan Collection'), (80, 'CC Loan Closing'), (81, 'Add Share AC'), (82, 'Delete CC Loan AC'), (83, 'Delete Share AC'), (84, 'Delete Share AC Transaction'), (85, 'Deposit Share AC'), (86, 'Withdraw Share AC'), (87, 'Profit Withdraw Share AC'), (88, 'Delete Special Savings AC Transaction'), (89, 'Deposit Special Savings AC'), (90, 'Withdraw Special Savings AC'), (91, 'Add Special Loan AC'), (92, 'Special Loan AC Closing'), (93, 'Delete Special Loan AC'), (94, 'Add Pass Book'), (95, 'Delete Pass Book'), (96, 'Edit General AC Transaction'), (97, 'Edit Loan Installment Collection'), (98, 'Transfer Share AC')], default=1),
        ),
    ]
