# Generated by Django 5.1 on 2024-08-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_userlog_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='cashflow_type',
            new_name='cashflow_type1',
        ),
        migrations.AddField(
            model_name='userlog',
            name='cashflow_type2',
            field=models.CharField(choices=[('receive', 'Receive'), ('payment', 'Payment')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
