# Generated by Django 5.1 on 2024-08-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_rename_cashflow_type_userlog_cashflow_type1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='cashflow_type1',
            field=models.CharField(choices=[('', ''), ('income', 'Income'), ('expense', 'Expense')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='cashflow_type2',
            field=models.CharField(choices=[('', ''), ('receive', 'Receive'), ('payment', 'Payment')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='transaction_type',
            field=models.CharField(choices=[('', ''), ('debit', 'Debit'), ('credit', 'Credit')], max_length=6),
        ),
    ]
