# Generated by Django 5.1 on 2024-08-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_customer_processed_by_and_more'),
        ('primary_setup', '0026_alter_vouchercategory_category_type'),
        ('report', '0005_alter_userlog_cashflow_type1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_setup.branch'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='cashflow_type1',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='cashflow_type2',
            field=models.CharField(blank=True, choices=[('receive', 'Receive'), ('payment', 'Payment')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.customer'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6, null=True),
        ),
    ]
