# Generated by Django 5.1 on 2024-08-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_userlog_amount_alter_userlog_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('add_member', 'Add Member'), ('admission_fee', 'Admission Fee'), ('admission_form_fee', 'Admission Form Fee')], max_length=300),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], max_length=10, null=True),
        ),
    ]
