# Generated by Django 5.1 on 2024-08-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_userlog_action_alter_userlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='logs_action',
            field=models.CharField(blank=True, choices=[('login', 'Login'), ('logout', 'Logout'), ('add_member', 'Add Member'), ('edit_member', 'Edit Member'), ('deposit_general_ac', 'Deposit General AC')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(blank=True, choices=[('admission_fee', 'Admission Fee'), ('admission_form_fee', 'Admission Form Fee'), ('deposit_general_ac_daily', 'Deposit General AC Daily'), ('deposit_general_ac_weekly', 'Deposit General AC Weekly'), ('deposit_general_ac_monthly', 'Deposit General AC Monthly')], max_length=300, null=True),
        ),
    ]
