# Generated by Django 5.1 on 2024-08-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_userlog_logs_action_alter_userlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='logs_action',
            field=models.CharField(blank=True, choices=[('login', 'Login'), ('logout', 'Logout'), ('add_member', 'Add Member'), ('edit_member', 'Edit Member'), ('deposit_general_ac', 'Deposit General AC'), ('withdraw_general_ac', 'Withdraw General AC'), ('deposit_special_ac', 'Deposit Special Savings AC'), ('withdraw_special_ac', 'Withdraw Special Savings AC'), ('add_loan_ac', 'Add Loan AC')], max_length=300, null=True),
        ),
    ]
