# Generated by Django 5.1 on 2024-08-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_userlog_action_alter_userlog_logs_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='logs_action',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
