# Generated by Django 5.1 on 2024-08-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_userlog_logs_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='trx',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
