# Generated by Django 5.1 on 2024-09-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_userlog_trx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
