# Generated by Django 5.1 on 2025-01-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_alter_userlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='VoucherID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
