# Generated by Django 5.1 on 2025-01-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_userlog_voucherid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
