# Generated by Django 5.1 on 2025-02-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0086_alter_generaldeposit_voucherid_and_more'),
        ('report', '0014_alter_userlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.loanac'),
        ),
    ]
