# Generated by Django 5.1 on 2024-08-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_loanac_loan_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanac',
            name='loan_scheme',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('half_monthly', 'Half Monthly'), ('monthly', 'Monthly')], max_length=100),
        ),
    ]
