# Generated by Django 5.1 on 2024-08-18 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_loanac_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_schedules', to='app1.loanac')),
            ],
        ),
        migrations.CreateModel(
            name='LoanCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(auto_now_add=True)),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.installmentschedule')),
            ],
        ),
    ]
