# Generated by Django 5.1 on 2024-08-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_installmentschedule_loancollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentschedule',
            name='skipped_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
