# Generated by Django 5.1 on 2024-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_installmentschedule_skipped_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanac',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanac',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loanac',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
