# Generated by Django 5.1 on 2024-08-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_loanac_end_date_loanac_paid_amount_loanac_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loancollection',
            old_name='amount_collected',
            new_name='Amount',
        ),
        migrations.RemoveField(
            model_name='loancollection',
            name='collection_date',
        ),
        migrations.RemoveField(
            model_name='loancollection',
            name='installment_schedule',
        ),
        migrations.AddField(
            model_name='loancollection',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loancollection',
            name='Note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loancollection',
            name='VoucherID',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loancollection',
            name='loan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan_collection', to='app1.loanac'),
        ),
        migrations.AddField(
            model_name='loancollection',
            name='processed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
