# Generated by Django 5.1 on 2024-08-19 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_amount_collected_loancollection_amount_and_more'),
        ('primary_setup', '0020_alter_customuser_is_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('dps_scheme', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('days90', '90 days'), ('years5', '5 Years')], max_length=100)),
                ('amount_per_installments', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_installments', models.IntegerField()),
                ('profit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('profit_taka', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fine_per_missed_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dps_opening_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_installment', models.IntegerField(default=0)),
                ('leger_no', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('installment_sequence', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='primary_setup.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
