# Generated by Django 5.1 on 2024-08-19 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_fdr'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPSInstallmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skipped_due_date', models.DateField(blank=True, null=True)),
                ('dps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdr_installment_schedules', to='app1.fdr')),
            ],
        ),
    ]
