# Generated by Django 5.1 on 2024-08-19 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_dpsinstallmentschedule'),
        ('primary_setup', '0020_alter_customuser_is_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FDR',
            new_name='DPS',
        ),
    ]
