# Generated by Django 5.1 on 2024-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_fdr_dps'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpsinstallmentschedule',
            name='installment_status',
            field=models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('---', '---')], default='---', max_length=4),
        ),
    ]
