# Generated by Django 5.1 on 2024-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_dpstransactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpstransactionhistory',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dpsdeposit',
            name='Fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dpswithdraw',
            name='Give_Profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
