# Generated by Django 5.1 on 2024-08-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_dpstransactionhistory_current_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentschedule',
            name='installment_status',
            field=models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('---', '---')], default='---', max_length=4),
        ),
    ]
