# Generated by Django 5.1 on 2024-08-20 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_installmentschedule_installment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanac',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='LoanFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Note', models.CharField(blank=True, max_length=200, null=True)),
                ('loan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loan_fine', to='app1.loanac')),
            ],
        ),
    ]
