# Generated by Django 5.1 on 2024-08-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_loanac_fine_loanfine'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentschedule',
            name='fine_applied',
            field=models.BooleanField(default=False),
        ),
    ]
