# Generated by Django 5.1 on 2024-08-20 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_installmentschedule_fine_applied'),
        ('primary_setup', '0020_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_CC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheme', models.CharField(choices=[('monthly', 'Monthly')], max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('profit_taka', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number_of_installments', models.IntegerField()),
                ('installment_sequence', models.CharField(blank=True, max_length=100, null=True)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_installment', models.IntegerField(default=0)),
                ('fine_per_missed_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('insurance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_form_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stamp_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stamp_information', models.TextField(blank=True, null=True)),
                ('bank_and_cheque_information', models.TextField(blank=True, null=True)),
                ('transaction_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('branch', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='primary_setup.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
                ('loan_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primary_setup.loancategory')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_CC_Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Note', models.CharField(blank=True, max_length=200, null=True)),
                ('VoucherID', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('processed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_cc_collection', to='app1.loan_cc')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_CC_InstallmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skipped_due_date', models.DateField(blank=True, null=True)),
                ('installment_status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('---', '---')], default='---', max_length=4)),
                ('fine_applied', models.BooleanField(default=False)),
                ('loan_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_cc_installment_schedules', to='app1.loanac')),
            ],
        ),
    ]
