# Generated by Django 5.1 on 2024-08-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_remove_loan_cc_collection_fine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_cc',
            old_name='scheme',
            new_name='loan_scheme',
        ),
    ]
