# Generated by Django 5.1 on 2024-08-20 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_loan_cc_installmentschedule_loan_cc'),
        ('primary_setup', '0020_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid')], default='active', max_length=100)),
                ('transaction_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('processed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_setup.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
            ],
        ),
    ]
