# Generated by Django 5.1 on 2024-08-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_loanac_status_alter_loan_special_collection_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanac',
            name='due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
