# Generated by Django 5.1 on 2024-08-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_loanac_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanac',
            name='due',
        ),
    ]
