# Generated by Django 5.1 on 2024-08-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_loan_cc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dps',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=100),
        ),
    ]
