# Generated by Django 5.1 on 2024-08-21 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_customer_processed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_target', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_withdraw', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Close', 'Close')], default='Active', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
            ],
        ),
    ]
