# Generated by Django 5.1 on 2024-08-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_generalac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='processed_by',
        ),
    ]
