# Generated by Django 5.1 on 2024-08-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_remove_customer_processed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='processed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
