# Generated by Django 5.1 on 2024-08-21 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_generalac_branch'),
        ('primary_setup', '0020_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalac',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_setup.branch'),
        ),
    ]
