# Generated by Django 5.1 on 2024-08-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_rename_starte_date_fdr_start_date_fdr_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdr',
            name='cheque',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fdr',
            name='monthly_profit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fdr',
            name='monthly_profit_taka',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fdr',
            name='nominee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
