# Generated by Django 5.1 on 2024-08-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_fdr_cheque_fdr_monthly_profit_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdr',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
