# Generated by Django 5.1 on 2024-08-22 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_alter_fdr_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDRTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('VoucherID', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('fdr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdr_transaction_history', to='app1.generalac')),
            ],
        ),
    ]
