# Generated by Django 5.1 on 2024-08-22 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_fdrtransactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdrtransactionhistory',
            name='fdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdr_transaction_history', to='app1.fdr'),
        ),
    ]
