# Generated by Django 5.1 on 2024-08-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_alter_fdrtransactionhistory_fdr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fdr',
            name='available_profit',
        ),
        migrations.RemoveField(
            model_name='fdr',
            name='total_profit',
        ),
    ]
