# Generated by Django 5.1 on 2024-08-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_fdrprofithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdr',
            name='last_profit_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProfitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_added', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('fdr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_history', to='app1.fdr')),
            ],
        ),
        migrations.DeleteModel(
            name='FDRProfitHistory',
        ),
    ]
