# Generated by Django 5.1 on 2024-08-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_fdr_last_profit_added_profithistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profithistory',
            name='added_on',
            field=models.DateField(),
        ),
    ]
