# Generated by Django 5.1 on 2024-08-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_alter_profithistory_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profithistory',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profithistory',
            name='current_profit_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
