# Generated by Django 5.1 on 2024-08-23 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_remove_dps_dps_scheme'),
        ('primary_setup', '0022_alter_fdrscheme_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dps',
            name='dps_scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='primary_setup.dpsscheme'),
        ),
    ]
