# Generated by Django 5.1 on 2024-08-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_dps_dps_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareAC',
            fields=[
                ('share_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nominee', models.CharField(max_length=255)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('withdraw', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('get_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_withdraw', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShareACTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('VoucherID', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('share_ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_ac_transaction_history', to='app1.shareac')),
            ],
        ),
    ]
