# Generated by Django 5.1 on 2024-08-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0060_banktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
