# Generated by Django 5.1 on 2024-08-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_alter_banktransaction_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='withdraw_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
