# Generated by Django 5.1 on 2024-08-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0062_banktransaction_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dps',
            name='dps_closing_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dps',
            name='dps_opening_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
