# Generated by Django 5.1 on 2024-08-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_loancollection_fine_loancollection_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpstransactionhistory',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
