# Generated by Django 5.1 on 2024-08-28 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0065_dpstransactionhistory_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareac',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
