# Generated by Django 5.1 on 2024-08-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0066_shareac_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loancollection',
            name='processed_by',
        ),
    ]
