# Generated by Django 5.1 on 2024-08-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0074_alter_banktransaction_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dps',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
