# Generated by Django 5.1 on 2024-09-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_customer_groups_customer_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_permissions',
        ),
    ]
