# Generated by Django 5.1 on 2024-09-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_remove_customer_groups_remove_customer_is_superuser_and_more'),
        ('primary_setup', '0031_alter_customuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activebranch',
            name='branch',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primary_setup.branch'),
        ),
    ]
