# Generated by Django 5.1 on 2024-09-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0078_alter_activebranch_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltransactionhistory',
            name='VoucherID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
