# Generated by Django 5.1 on 2024-09-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0080_savingstransactionhistory_voucherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpstransactionhistory',
            name='VoucherID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
