# Generated by Django 5.1 on 2024-10-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0081_dpstransactionhistory_voucherid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, default='1234', max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('billing_cycle', models.CharField(blank=True, default='Monthly', max_length=50, null=True)),
                ('package_name', models.CharField(blank=True, max_length=100, null=True)),
                ('limit_customer', models.CharField(blank=True, default='100', max_length=100, null=True)),
            ],
        ),
    ]
