# Generated by Django 5.1 on 2024-12-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0083_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='somity_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
