# Generated by Django 5.1 on 2025-01-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0085_alter_loancollection_voucherid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldeposit',
            name='VoucherID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='generalwithdraw',
            name='VoucherID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
